name: Build and Release Artifact

on:
  push:
    branches:
      - main
      - v2

jobs:
  build-and-upload:
    name: Build and Upload Artifact
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
          cache-dependency-path: yarn.lock
          cache-path: ~/.cache/yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build the project
        run: yarn build --mode development

      - name: Package the build into a tarball
        run: |
          cd build/ && tar -zcvf ../console-dev.tgz --exclude='./data' .

      - name: Upload the artifact
        uses: actions/upload-artifact@v3
        with:
          name: console-dev-artifact
          path: ./console-dev.tgz
