name: skupper-console
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        env:
            ENABLE_MOCK_SERVER: true
            API_HOST: ${{secrets.API_HOST}}
            API_HOST_FLOW_COLLECTOR: ${{secrets.API_HOST_FLOW_COLLECTOR}}
        steps:
            - name: Checkout 🛎️
              uses: actions/checkout@v3

            - name: Install 📦
              run: |
                  yarn install --frozen-lockfile

            - name: Lint 🎨
              run: |
                  yarn lint

            - name: Build 🚧
              run: |
                  yarn build

            - name: Unit tests 🔧
              run: |
                  yarn test

            - name: Integration tests 🚨
              run: |
                  yarn ci
